version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: heavy_lift
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: heavy_lift
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
